/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddEditProduct: typeof import('./src/components/AddEditProduct.vue')['default']
    AddProduct: typeof import('./src/components/AddProduct.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NavMenu: typeof import('./src/components/NavMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
